export default {
	//Autorization
	AUTORIZATION: 'AUTORIZATION',
	AUTORIZATION_ERROR: 'AUTORIZATION_ERROR',
	GET_TOKEN_FROM_SERVER: 'GET_TOKEN_FROM_SERVER',
	//Content
	LOAD_DATA: 'LOAD_DATA',
	LOAD_MOVIES: 'LOAD_MOVIES',
	LOAD_SCHEDULE: 'LOAD_SCHEDULE'
}